"""configuracion empresa y perfil de usuario

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 17:24:00.813359

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy  # noqa: F401 - columnas Vector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('nit', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email_contacto', sa.String(length=150), nullable=True),
    sa.Column('sitio_web', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usuarios', sa.Column('username', sa.String(length=30), nullable=True))
    op.add_column('usuarios', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('usuarios', sa.Column('telefono', sa.String(length=30), nullable=True))
    op.add_column('usuarios', sa.Column('cargo', sa.String(length=100), nullable=True))
    op.create_unique_constraint('usuarios_username_key', 'usuarios', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usuarios_username_key', 'usuarios', type_='unique')
    op.drop_column('usuarios', 'cargo')
    op.drop_column('usuarios', 'telefono')
    op.drop_column('usuarios', 'avatar_url')
    op.drop_column('usuarios', 'username')
    op.drop_table('empresa')
    # ### end Alembic commands ###
